### ISSUE TITLE
Builiding Problem

### ISSUE THREAD

**Issue by thlengane** [xiaocong/android-uiautomator-server#1]
Hi @xiaocong 

I am trying  to build this using gradle but I am stuck on some <b>nanohttpd</b>, <b>jsonrpc4j</b> and <b>jackson</b>  dependency problem. Please help. How do I point the project to the right address/repository?

Here are the errors I am getting:-

<b>FAILURE: Build failed with an exception.</b>

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugAndroidTestCompile'.
   > Could not resolve com.nanohttpd:nanohttpd:2.1.1.
     Required by:
         android-uiautomator-server-master:app:unspecified
      > Could not resolve com.nanohttpd:nanohttpd:2.1.1.
         > Could not get resource 'https://jcenter.bintray.com/com/nanohttpd/nanohttpd/2.1.1/nanohttpd-2.1.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/nanohttpd/nanohttpd/2.1.1/nanohttpd-2.1.1.pom'.
               > Connection to https://jcenter.bintray.com refused
      > Could not resolve com.nanohttpd:nanohttpd:2.1.1.
         > Could not get resource 'https://repo1.maven.org/maven2/com/nanohttpd/nanohttpd/2.1.1/nanohttpd-2.1.1.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/com/nanohttpd/nanohttpd/2.1.1/nanohttpd-2.1.1.pom'.
               > Connection to https://repo1.maven.org refused
   > Could not resolve com.fasterxml.jackson.core:jackson-core:2.5.3.
     Required by:
         android-uiautomator-server-master:app:unspecified
      > Could not resolve com.fasterxml.jackson.core:jackson-core:2.5.3.
         > Could not get resource 'https://jcenter.bintray.com/com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.pom'.
               > Connection to https://jcenter.bintray.com refused
      > Could not resolve com.fasterxml.jackson.core:jackson-core:2.5.3.
         > Could not get resource 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.pom'.
               > Connection to https://repo1.maven.org refused
   > Could not resolve com.fasterxml.jackson.core:jackson-annotations:2.5.3.
     Required by:
         android-uiautomator-server-master:app:unspecified
      > Could not resolve com.fasterxml.jackson.core:jackson-annotations:2.5.3.
         > Could not get resource 'https://jcenter.bintray.com/com/fasterxml/jackson/core/jackson-annotations/2.5.3/jackson-annotations-2.5.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/fasterxml/jackson/core/jackson-annotations/2.5.3/jackson-annotations-2.5.3.pom'.
               > Connection to https://jcenter.bintray.com refused
      > Could not resolve com.fasterxml.jackson.core:jackson-annotations:2.5.3.
         > Could not get resource 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.5.3/jackson-annotations-2.5.3.po
            > Could not GET 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.5.3/jackson-annotations-2.5.3.pom'.
               > Connection to https://repo1.maven.org refused
   > Could not resolve com.fasterxml.jackson.core:jackson-databind:2.5.3.
     Required by:
         android-uiautomator-server-master:app:unspecified
      > Could not resolve com.fasterxml.jackson.core:jackson-databind:2.5.3.
         > Could not get resource 'https://jcenter.bintray.com/com/fasterxml/jackson/core/jackson-databind/2.5.3/jackson-databind-2.5.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/fasterxml/jackson/core/jackson-databind/2.5.3/jackson-databind-2.5.3.pom'.
               > Connection to https://jcenter.bintray.com refused
      > Could not resolve com.fasterxml.jackson.core:jackson-databind:2.5.3.
         > Could not get resource 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.5.3/jackson-databind-2.5.3.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.5.3/jackson-databind-2.5.3.pom'.
               > Connection to https://repo1.maven.org refused
   > Could not resolve com.github.briandilley.jsonrpc4j:jsonrpc4j:1.1.
     Required by:
         android-uiautomator-server-master:app:unspecified
      > Could not resolve com.github.briandilley.jsonrpc4j:jsonrpc4j:1.1.
         > Could not get resource 'https://jcenter.bintray.com/com/github/briandilley/jsonrpc4j/jsonrpc4j/1.1/jsonrpc4j-1.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/github/briandilley/jsonrpc4j/jsonrpc4j/1.1/jsonrpc4j-1.1.pom'.
               > Connection to https://jcenter.bintray.com refused
      > Could not resolve com.github.briandilley.jsonrpc4j:jsonrpc4j:1.1.
         > Could not get resource 'https://repo1.maven.org/maven2/com/github/briandilley/jsonrpc4j/jsonrpc4j/1.1/jsonrpc4j-1.1.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/com/github/briandilley/jsonrpc4j/jsonrpc4j/1.1/jsonrpc4j-1.1.pom'.
               > Connection to https://repo1.maven.org refused
   > Could not resolve javax.servlet:servlet-api:2.5.
     Required by:
         android-uiautomator-server-master:app:unspecified
      > Could not resolve javax.servlet:servlet-api:2.5.
         > Could not get resource 'https://jcenter.bintray.com/javax/servlet/servlet-api/2.5/servlet-api-2.5.pom'.
            > Could not GET 'https://jcenter.bintray.com/javax/servlet/servlet-api/2.5/servlet-api-2.5.pom'.
               > Connection to https://jcenter.bintray.com refused
      > Could not resolve javax.servlet:servlet-api:2.5.
         > Could not get resource 'https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.pom'.
               > Connection to https://repo1.maven.org refused
   > Could not resolve javax.portlet:portlet-api:2.0.
     Required by:
         android-uiautomator-server-master:app:unspecified
      > Could not resolve javax.portlet:portlet-api:2.0.
         > Could not get resource 'https://jcenter.bintray.com/javax/portlet/portlet-api/2.0/portlet-api-2.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/javax/portlet/portlet-api/2.0/portlet-api-2.0.pom'.
               > Connection to https://jcenter.bintray.com refused
      > Could not resolve javax.portlet:portlet-api:2.0.
         > Could not get resource 'https://repo1.maven.org/maven2/javax/portlet/portlet-api/2.0/portlet-api-2.0.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/javax/portlet/portlet-api/2.0/portlet-api-2.0.pom'.
               > Connection to https://repo1.maven.org refused
   > Could not resolve junit:junit-dep:4.10.
     Required by:
         android-uiautomator-server-master:app:unspecified > com.android.support.test:runner:0.2
      > Could not resolve junit:junit-dep:4.10.
         > Could not get resource 'https://jcenter.bintray.com/junit/junit-dep/4.10/junit-dep-4.10.pom'.
            > Could not GET 'https://jcenter.bintray.com/junit/junit-dep/4.10/junit-dep-4.10.pom'.
               > Connection to https://jcenter.bintray.com refused
      > Could not resolve junit:junit-dep:4.10.
         > Could not get resource 'https://repo1.maven.org/maven2/junit/junit-dep/4.10/junit-dep-4.10.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/junit/junit-dep/4.10/junit-dep-4.10.pom'.
               > Connection to https://repo1.maven.org refused

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

<b>BUILD FAILED</b>

Total time: 1 mins 16.99 secs

**Comment by xiaocong** [comment]
could u check if ur internet connection is ok?

**Comment by thlengane** [comment]
@xiaocong 

Internet is working fine, see below..

c:\Automation\ui_test\android-uiautomator-server-master><b>curl http://www.google.co.za</b>

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-ZA"><head><meta content="/images/google_favicon_128.png" itemprop="image"><title>Google</title><script>(functi
on(){window.google={kEI:'XLdtVYW_Nq2v7AaezoP4Dg',kEXPI:'3700325,4017578,4025836,4026110,4029570,4029815,4030125,4031300,4031637,4032500,4032522,4032643,4032645,4032678,4032711,4033307,403334
4,4034425,4034617,4034884,4035816,4036486,4036540,4036665,4037457,4037995,8300096,8300154,8500394,8500972,8501248,8501295,8501351,8501406,8501489,8501594,10200083,10201089,10201180',authuser
:0,kscs:'c9c918f0_10'};google.kHL='en-ZA';})();(function(){google.lc=[];google.li=0;google.getEI=function(a){for(var b;a&&(!a.getAttribute||!(b=a.getAttribute("eid")));)a=a.parentNode;return
 b||google.kEI};google.getLEI=function(a){for(var b=null;a&&(!a.getAttribute||!(b=a.getAttribute("leid")));)a=a.parentNode;return b};google.https=function(){return"https:"==window.location.p
rotocol};google.ml=function(){};google.time=function(){return(new Date).getTime()};google.log=function(a,b,e,f,l){var d=new Image,h=google.lc,g=google.li,c="",m=google.ls||"";d.onerror=d.onl
oad=d.onabort=function(){delete h[g]};h[g]=d;if(!e&&-1==b.search("&ei=")){var k=google.getEI(f),c="&ei="+k;-1==b.search("&lei=")&&((f=google.getLEI(f))?c+="&lei="+f:k!=google.kEI&&(c+="&lei=
"+google.kEI))}a=e||"/"+(l||"gen_204")+"?atyp=i&ct="+a+"&cad="+b+c+m+"&zx="+google.time();/^http:/i.test(a)&&google.https()?(google.ml(Error("a"),!1,{src:a,glmm:1}),delete h[g]):(window.goog
le&&window.google.vel&&
window.google.vel.lu&&window.google.vel.lu(a),d.src=a,google.li=g+1)};google.y={};google.x=function(a,b){google.y[a.id]=[a,b];return!1};google.load=function(a,b,e){google.x({id:a+n++},functi
on(){google.load(a,b,e)})};var n=0;})();google.kCSI={};var _gjwl=location;function _gjuc(){var a=_gjwl.href.indexOf("#");if(0<=a&&(a=_gjwl.href.substring(a),0<a.indexOf("&q=")||0<=a.indexOf(
"#q="))&&(a=a.substring(1),-1==a.indexOf("#"))){for(var d=0;d<a.length;){var b=d;"&"==a.charAt(b)&&++b;var c=a.indexOf("&",b);-1==c&&(c=a.length);b=a.substring(b,c);if(0==b.indexOf("fp="))a=
a.substring(0,d)+a.substring(c,a.length),c=d;else if("cad=h"==b)return 0;d=c}_gjwl.href="/search?"+a+"&cad=h";return 1}return 0}
function _gjh(){!_gjuc()&&window.google&&google.x&&google.x({id:"GJH"},function(){google.nav&&google.nav.gjh&&google.nav.gjh()})};window._gjh&&_gjh();</script><style>#gbar,#guser{font-size:1
3px;padding-top:1px !important;}#gbar{height:22px}#guser{padding-bottom:7px !important;text-align:right}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;t
op:24px;width:100%}@media all{.gb1{height:22px;margin-right:.5em;vertical-align:top}#gbar{float:left}}a.gb1,a.gb4{text-decoration:underline !important}a.gb1,a.gb4{color:#00c !important}.gbi
.gb4{color:#dd8e27 !important}.gbf .gb4{color:#900 !important}</style><style>body,td,a,p,.h{font-family:arial,sans-serif}body{margin:0;overflow-y:scroll}#gog{padding:3px 8px 0}td{line-height
:.8em}.gac_m td{line-height:17px}form{margin-bottom:20px}.h{color:#36c}.q{color:#00c}.ts td{padding:0}.ts{border-collapse:collapse}em{font-weight:bold;font-style:normal}.lst{height:25px;widt
h:496px}.gsfi,.lst{font:18px arial,sans-serif}.gsfs{font:17px arial,sans-serif}.ds{display:inline-box;display:inline-block;margin:3px 0 4px;margin-left:4px}input{font-family:inherit}a.gb1,a.
gb2,a.gb3,a.gb4{color:#11c !important}body{background:#fff;color:black}a{color:#11c;text-decoration:none}a:hover,a:active{text-decoration:underline}.fl a{color:#36c}a:visited{color:#551a8b}a
.gb1,a.gb4{text-decoration:underline}a.gb3:hover{text-decoration:none}#ghead a.gb2:hover{color:#fff !important}.sblc{padding-top:5px}.sblc a{display:block;margin:2px 0;margin-left:13px;font-
size:11px}.lsbb{background:#eee;border:solid 1px;border-color:#ccc #999 #999 #ccc;height:30px}.lsbb{display:block}.ftl,#fll a{display:inline-block;margin:0 12px}.lsb{background:url(/images/s
rpr/nav_logo80.png) 0 -258px repeat-x;border:none;color:#000;cursor:pointer;height:30px;margin:0;outline:0;font:15px arial,sans-serif;vertical-align:top}.lsb:active{background:#ccc}.lst:focu
s{outline:none}</style><script></script></head><body bgcolor="#fff"><script>(function(){var src='/images/nav_logo199.png';var iesg=false;document.body.onload = function(){window.n && window.
n();if (document.images){new Image().src=src;}.........................................
..........................

**Comment by thlengane** [comment]
Hi @xiaocong 

I managed to fix this. I had to set the HTTPS proxy on gradle. For some reason, it was not picking up the default proxy and on my cmd, I was only setting HTTP.

Here is the solution in case anyone comes across this problem:

gradle -Dhttp.proxyHost=<<b><i>proxy</b></i>>  -Dhttp.proxyPort=<<b><i>port</i></b>> -Dhttps.proxyHost=<<b><i>proxy</b></i>>  -Dhttps.proxyPort=<<b><i>port</b></i>> build

**Comment by xiaocong** [comment]
Great :+1:
