### ISSUE TITLE
Building 94% > :app:connectedAndroidTestDebug 

### ISSUE THREAD

**Issue by llliuyx** [xiaocong/android-uiautomator-server#21]
Hello,
I follow your steps, but when executing ./gradew cC, the building stays in here, not build any more.
I do not find any exception or error.

:app:preDexDebugAndroidTest UP-TO-DATE
:app:dexDebugAndroidTest UP-TO-DATE
:app:packageDebugAndroidTest UP-TO-DATE
:app:assembleDebugAndroidTest UP-TO-DATE
> Building 94% > :app:connectedAndroidTestDebug

Thank you.
Best wishes!!!

**Comment by thlengane** [comment]
Follow this to get going..

https://github.com/xiaocong/android-uiautomator-server/wiki/Force-Start-Json-Server
