### ISSUE TITLE
Protocol on the rpc interface

### ISSUE THREAD

**Issue by yifeikong** [xiaocong/android-uiautomator-server#23]
I'm interested in communicating with the rpc server, but I'm not familiar with java, could you please offer a simple guide on how the protocol is?

**Comment by Scisaga** [comment]
I'm interested in communicating with the rpc server, but I'm not familiar with python, could u pls offer a simple api design specification? I am interested in make a java version client, have you been working around something related? pls tell me. thx.

**Comment by yifeikong** [comment]
the rpc interface is actually lying in the codes, you just have to have a little understanding of Java. It's not that hard.

After that, I have rewritten a server and a client in Java, but I can't share too much with you, cause it's a proprietary software

**Comment by Scisaga** [comment]
@yifeikong thanks for your reply, it seems i would rewrite this project by myself, if u can share some experiences and prone mistakes during rewriting the server and client that will be much helpful.

**Comment by Scisaga** [comment]
@yifeikong BTW, did u notice that when current page contain webview, using uiautomator will not get element hierarchy inside webview for the first time, but the 2nd time will be ok.
i don't know if it's a uiautomator bug or i misconfigure something.

**Comment by yifeikong** [comment]
@Scisaga My architecture goes like this:

`simulate steps script(local) --> http Server <-- Client(Android apk) <--rpc--> Server(Android apk)`

which means, I write a simulate touch script on my local computer, and pushes it to the http server. then the client on android pulls data from the http server, it interprets the script and instruct the ui automator server to run it.

the tricky part is that you never call android server on your local computer, let your phone invoke a http api to pull data.

and the most elegant part I found is that in my implementation, the script is actually yaml file.
