### ISSUE TITLE
Why is the server not directly accessible?

### ISSUE THREAD

**Issue by yifeikong** [xiaocong/android-uiautomator-server#24]
I opened the server on Android, but instead of using `adb forward`, I tried to access `192.168.x.x:9008`, which is android's wifi ip address.

    curl -d '{"jsonrpc":"2.0","method":"ping","id":1}' 192.168.99.206:9008/jsonrpc/0

but I got `Failed to connect to 192.168.99.206 port 9008: Connection refused`, why is the rpc server not directly accessible?

**Comment by yifeikong** [comment]
I figured it out, there is a bug in your code, and using `adb forward` just buried the bug

**Comment by Scisaga** [comment]
@yifeikong which kind of bug?

**Comment by yifeikong** [comment]
@Scisaga I'm still not sure, you could try to add wifi permission to the manifest.

The idea of setting up a rpc server on android and listening on PC in not stable at all. Instead, I'm now running a client on android itself to communicating with the server. So this is no longer a problem for me.

**Comment by Scisaga** [comment]
@yifeikong I still didn't get the idea of forwarding a android device port to pc, it will facilitate testing procedure which you can just access 127.0.0.1 based address?
